# Generated by Django 3.1.4 on 2021-01-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery', '0002_plat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plat',
            new_name='Plant',
        ),
    ]
