# Generated by Django 3.1.4 on 2021-01-02 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nursery', '0003_auto_20210102_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurseryName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='PlantImage')),
                ('price', models.FloatField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
