# Generated by Django 3.1.4 on 2021-01-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery', '0006_remove_nurseryplant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
