# Generated by Django 3.1.4 on 2021-01-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='buyer',
        ),
    ]
